name: fluent_widgets
description: "A collection of Fluent UI widgets."
version: 0.1.4
homepage: https://github.com/ConcenTech/fluent_widgets
issue_tracker: https://github.com/ConcenTech/fluent_widgets/issues
documentation: https://github.com/ConcenTech/fluent_widgets/blob/main/README.md

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.13.0
  uuid: ^4.5.1
  pausable_timer: ^3.1.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
